### ISSUE TITLE
Error al tratar de instalar en la versión 10.0

### ISSUE THREAD

**Issue by guillermm** [laotraopcion/meli_oerp#1]
Hola, @celm1990 como te va?.

Trate de instalar las últimas modificaciones que habías hecho y me sale el siguiente error.

![pantallazo-2018-04-09 11-50-14](https://user-images.githubusercontent.com/18652795/38511160-d80cf9f0-3bec-11e8-98ed-d3ef3d667063.png)

Saludos y gracias.

**Comment by celm1990** [comment]
Estimado @guillermm te pediria que actualices tu repo con los ultimos cambios. En este commit b66643c1d9bdd0b5aade3f2c5783caf6c455b708 se agregan los objetos de los que te sale error, vi tu fork y no esta actualizado con los 3 ultimos commit.

Actualiza el repo, reincia tu instancia de odoo y envia a actualizar el modulo, me cuentas como te va

**Comment by guillermm** [comment]
Hola, @celm1990 si debo actualizar, pero yo hice un **git clone** directamente de tu branch he hice las pruebas con el código reciente. y esa es la pantalla de hoy temprano. Saludos

**Comment by celm1990** [comment]
Probe en una instalacion desde 0 y no obtuve ningun error, insisto que actualices el repo, si es posible dejame ver el ultimo commit que tienes localmente.

**Comment by celm1990** [comment]
Acabo de subir un commit para agregar una dependencia al modulo de stock, pero no es el mismo mensaje q te sale a ti, podrias bajar cambios e intentar de nuevo y ver si eso soluciona tu problema.

**Comment by guillermm** [comment]
Hola. 

Estimado Carlos monte los últimos cambios que hiciste y va excelente!. Que gran trabajo has hecho, te felicito!.

**Comment by celm1990** [comment]
Listo, cierro el bug entonces
