### ISSUE TITLE
Error al tratar de publicar por segunda vez y repetidas veces en la versión 10.0

### ISSUE THREAD

**Issue by guillermm** [laotraopcion/meli_oerp#2]
Hola, estimado @celm1990 espero que te encuentres bien. 
Te escribo para comentarte acerca de algo extraño que me pasa al tratar de publicar una segunda vez y otros articulo del stock, no sale ningún error simplemente no publica ni aparece los botones de actualizar, pausar, cancelar, o eliminar publicación.

![pantallazo-2018-04-12 11-46-53](https://user-images.githubusercontent.com/18652795/38695377-b35961ea-3e51-11e8-8985-c2f7c445616c.png)

Y esto es lo que me sale en el log.

![pantallazo-2018-04-12 13-02-45](https://user-images.githubusercontent.com/18652795/38697100-9e3007ce-3e56-11e8-8eb2-b62679745a1b.png)

Que puede ser eso tan extraño?

**Comment by celm1990** [comment]
Hola,

Esto mas bien parece un error de la libreria urllib3, puedes indicar que version de esa libreria tienes??
![image](https://user-images.githubusercontent.com/7775116/38697941-0299f970-3e59-11e8-9034-5e1b0251ea80.png)

**Comment by guillermm** [comment]
Lo más extraño @celm1990 es que el funcionaba el primer dia, y el log que arroja es este:

turbodiesel@gavilan:~$ sudo pip install urllib3 --upgrade
The directory '/home/turbodiesel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/turbodiesel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: urllib3 in /usr/local/lib/python2.7/dist-packages
turbodiesel@gavilan:~$ sudo pip install urllib3[secure]
The directory '/home/turbodiesel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/turbodiesel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: urllib3[secure] in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: certifi; extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: ipaddress; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])

La versión del Python es :  2.7.6

**Comment by celm1990** [comment]
Estas son las versiones de las librerias que yo tengo y me funciona bien a mi:
python==2.7.12
urllib3==1.22
cryptography==1.4
six==1.10.0
pycparser==2.14

Las otras librerias que salen en tu log y que no las mensiono aca, es xq yo no las tengo instaladas(imagino q alguna otra libreria te las instala a ti pero no son necesarias aca).
Compara las versiones que tu tienes y actualiza de ser necesario, me cuentas como te va.

**Comment by guillermm** [comment]
Hola, estimado @celm1990 si veo que tengo un problema a nivel de paquetes y librerías. Estuve viendo un poco sobre la versión de urllib3 y estando el python menor a la versión 2.7.9, teniendo yo la 2.7.6 esta no soporta bien lo de SSL y da ciertos errores de autenticación "/usr/local/lib/python2.7/dist-packages/pip/vendor/urllib3/util/ssl.py:339: SNIMissingWarning"  y esto se corrige desde la versión 2.7.9 en adelante. Voy a probar una instancia nueva con paquetes iguales o superiores a tus versiones y voy a probar, y te estaré contando como me va. 

Muchas gracias por tu gran ayuda.

Saludos Carlos,

**Comment by celm1990** [comment]
lissto, cierro el issue entonces xq no es algo del modulo sino de librerias
