### ISSUE TITLE
No actualiza titulo, precio ni descripción del producto.

### ISSUE THREAD

**Issue by guillermm** [laotraopcion/meli_oerp#3]
Hola, Carlos.

Buenos días, gracias por responderme. Dejame felicitarte por la excelente evolución de tu desarrollo, ha cambiado drasticamente, te mando unas capturas para explicarte mejor. 

Lo que se desea es que al publicar, en determinado tiempo si se desea o si el usuario se equivoca, que nos permita editar cambiando el título, precio y descripción. Como se muestra a continuación, marco los campos cambiados. El título se trata de modificar actualizandolo, pero cuando se le da al botón <Actualizar producto en ML>  vuelve a retornar el mismo que tiene la publicación cuando se creo inicialmente y no se actualiza en ML, con el precio se cambia en odoo pero no actualiza en ML al igual que la descripción al precionar el botón <Actualizar producto en ML>. 

![cap_01](https://user-images.githubusercontent.com/18652795/46017373-f0ab7600-c09c-11e8-8d9e-fcda9a875bc6.jpg)

Deseo cambiar el titulo, el precio o la descripción y no cambia como muestra en la siguiente pantalla.

![cap_02](https://user-images.githubusercontent.com/18652795/46017390-f739ed80-c09c-11e8-9680-068f19784b5f.jpg)

No se si se trate de pasos que me este saltando, ya que el articulo se crea correctamente y sube las imagenes, cambia de estados perfectamente a pausado y a activo. Entiendo que la cantidad no puede editarse al tener ciertos permisos como lideres o que tengan tiempo vendiendo en ml como vendeores plata y oro.

Saludos Carlos y Gracias.

**Comment by tdcomcl** [comment]
Hola, tengo mismo problema. Hay alguna solución? 

Saludos

**Comment by guillermm** [comment]
Hola, @tdcomcl, espero que te pueda servir.

@celm1990 Se puede cerrar este issue. 
Ya se puede hacer esta acción. Se puede modificar con unos pequeños cambios en la función _product_update_to_meli()_ , les dejo el link para que comparen.
https://github.com/guillermm/meli_oerp/blob/10.0/models/product.py

Se hicieron las siguientes modificaciones:
https://github.com/guillermm/meli_oerp/blob/eafbd69da40d5af7a616ebc6d8b3bcddb7848023/models/product.py#L812

https://github.com/guillermm/meli_oerp/blob/eafbd69da40d5af7a616ebc6d8b3bcddb7848023/models/product.py#L824-L830

https://github.com/guillermm/meli_oerp/blob/eafbd69da40d5af7a616ebc6d8b3bcddb7848023/models/product.py#L901-L904

Esta versión la estamos adaptando para Colombia y se comentó algunas funcionalidades para la versión para Chile que se trabaja originalmente, aclarando que la versión inicial es de Argentina. Estas modificaciones son temporales ya que nuestra intención es hacerla que se adapte a cualquier pais que opera con ML.

**Comment by tdcomcl** [comment]
Hola, Primero que nada ! Gracias.. 
depuest de hacer los cambios me entrea el sigueinte error ! 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 1336, in load_views
    for [v_id, v_type] in views
  File "/odoo/odoo-server/odoo/models.py", line 1336, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 364, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo/odoo-server/odoo/models.py", line 1415, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 916, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 474, in raise_view_error
    raise ValueError(message)
ValueError: El campo `meli_id` no existe

Error de contexto:
Vista `product.template.product.tree`
[view_id: 402, xml_id: product.product_template_tree_view, model: product.template, parent_id: n/a]

Saludos°

**Comment by guillermm** [comment]
Hola, @tdcomcl.
Explicame en detalle que hicistes, ¿para qué país lo estas configurando?, si puedes colocar capturas de pantallas seria mucho mejor para entender mejor lo que esta pasando. Has podido publicar?  porque parece ser que es un error por falta de configuración.

**Comment by tdcomcl** [comment]
Solucionado.. fue un error mio. 

Gracias
